# Generated by Django 3.0.5 on 2020-04-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200426_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/None/default.jpg', upload_to='profile_img'),
        ),
    ]
