# Generated by Django 3.0.5 on 2020-04-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genres',
        ),
        migrations.AddField(
            model_name='genre',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
