# Generated by Django 3.0.5 on 2020-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_cover',
            field=models.ImageField(blank=True, default='images/None/no-img.jpg', upload_to='cover_img'),
        ),
    ]
